<template>
  <div>
    <h1>詳細</h1>
    <h2>アプリの概要</h2>
    <p>自分がこれまでACした問題のACした回数を表示し、復習を助けるWEBアプリです</p>
    <h2>仕様</h2>
    <p>ALLのタブではこれまでACした問題のACした回数とリンクが未定義で並べられます。</p>
    <p>A～FのタブではこれまでACした問題のACした回数の昇順、同じAC数の中では最後にACした時間が一番古いものから並べられます。</p>
    <h2>諸注意</h2>
    <p>
      このアプリは
      <a
        href="https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md"
        target="_blank"
      >AtCoder Problems API</a> および AtCoder APIを利用して作成されています。
      先方にも注意事項としてあるように無理なAPIリクエストは避けてください。より具体的には検索ボタン連打等は止めてください。
      節度を守って利用しましょう。
      自分の実装力がアレすぎて現状はAとかEって付く問題しか分類できてません。いずれは改良したいと思います...
    </p>
    <h2>その他</h2>
    <p>WEBアプリ何もわかりません。アドバイスや提案をプルリクやTwitterで投げてくれると有難いです。</p>
  </div>
</template>
